#!/usr/bin/env bash
clear

FOLDER=$HOME/.ubuntu-instalador

source $FOLDER/sources/adicionarPPA.sh
source $FOLDER/sources/gerenciadorPPA.sh
source $FOLDER/sources/posInstalacao.sh
source $FOLDER/sources/instalarPrograma.sh
source $FOLDER/sources/atualizarSistema.sh
source $FOLDER/sources/adicionarVirtualhost.sh
source $FOLDER/sources/gitRepositorio.sh
source $FOLDER/sources/iniciarGit.sh
source $FOLDER/sources/clonarGit.sh
source $FOLDER/sources/criarProjeto.sh

main() {
	if [ -z "${1}" ]; then
		echo "Escolha a opção:";
		echo "1 - Instalar programas pós-instalação de sistema."
		echo "2 - Instalar um programa."
		echo "3 - Atualizar sistemas."
		echo "4 - Criar projetos para programação."
		echo "5 - Sair."

		read opcao;
	else
		opcao=$1
	fi

	case $opcao in
		1) posInstalacao ;;
		2) instalarPrograma ;;
		3) atualizarSistema ;;
		4) projetos ;;
		5) exit ;;
		*) echo "Opcao desconhecida."; main ;;
	esac
}

versionamentoGit() {
	echo "Escolha a opção:";
	echo "1 - Criar um repositório."
	echo "2 - Clonar um repositório."
	echo "3 - Retornar ao main anterior."
	echo "4 - Sair."
	read opcao

	case $opcao in
		1) echo "--> Digite a pasta do projeto."; read dir; iniciarGit $dir ;;
		2) clonarGit ;;
		3) projetos ;;
		4) exit ;;
		*) echo "Opcao desconhecida."; versionamentoGit ;;
	esac
}

projetos () {
	# Define a pasta de projetos
	dir_projetos="${HOME}/Dev/Web"

	echo "Escolha a opção:";
	echo "1 - Criar projeto."
	echo "2 - Adicionar VirtualHost."
	echo "3 - Versionamento com GIT."
	echo "4 - Retornar ao main principal."
	echo "5 - Sair."
	read opcao

	case $opcao in
		1) criarProjeto ;;
		2) echo "--> Digite o nome do virtualhost."; read vh; adicionarVirtualhost $vh ;;
		3) versionamentoGit $dir ;;
		4) main ;;
		5) exit ;;
		*) echo "Opcao desconhecida."; projetos ;;
	esac
}

# Inicia o programa invocando o main
main $1
exit
